package com.myspace.switchingschedule;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AssetStateAction implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Closed, Opened, Enabled, Disabled, etc")
	private java.lang.String state;
	@org.kie.api.definition.type.Label("Close, Open, Enable, Disable, etc")
	private java.lang.String action;
	@org.kie.api.definition.type.Label("The PoF ActionVerb that represents the state for that asset")
	private java.lang.String actionVerb;
	@org.kie.api.definition.type.Label(value = "The PoF ActionName (Code) that represents the state for that asset")
	private java.lang.String actionName;

	public AssetStateAction() {
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getAction() {
		return this.action;
	}

	public void setAction(java.lang.String action) {
		this.action = action;
	}

	public java.lang.String getActionVerb() {
		return this.actionVerb;
	}

	public void setActionVerb(java.lang.String actionVerb) {
		this.actionVerb = actionVerb;
	}

	public java.lang.String getActionName() {
		return this.actionName;
	}

	public void setActionName(java.lang.String actionName) {
		this.actionName = actionName;
	}

	public AssetStateAction(java.lang.String state, java.lang.String actionVerb,
			java.lang.String actionName) {
		this.state = state;
		this.actionVerb = actionVerb;
		this.actionName = actionName;
	}

}